/**
 * Gong voices available for the timer cues.
 *
 * The two samples are single strikes cut out of the source recordings by
 * scripts/prepare-gongs.sh, loudness-matched and tail-faded. `synth` needs no
 * file at all — it is generated by the Web Audio engine.
 */

export const GONGS = [
  { id: 'gong-1', name: 'Gong 1', hint: 'Frappe courte, 5 s', url: '/gongs/gong-1.mp3' },
  { id: 'gong-2', name: 'Gong 2', hint: 'Résonance longue, 9 s', url: '/gongs/gong-2.mp3' },
  { id: 'synth', name: 'Synthétique', hint: 'Cloche générée, sans fichier', url: null },
];

export function findGong(id) {
  return GONGS.find((g) => g.id === id) || GONGS[0];
}
