/**
 * Gong voices available for the timer cues.
 *
 * The two samples are single strikes cut out of the source recordings by
 * scripts/prepare-gongs.sh, loudness-matched and tail-faded. `synth` needs no
 * file at all — it is generated by the Web Audio engine.
 */

export const GONGS = [
  { id: 'gong-1', name: 'Gong 1', hint: 'Frappe courte, 5 s', url: '/gongs/gong-1.mp3' },
  { id: 'gong-2', name: 'Gong 2', hint: 'Résonance longue, 9 s', url: '/gongs/gong-2.mp3' },
  { id: 'synth', name: 'Synthétique', hint: 'Cloche générée, sans fichier', url: null },
];

/**
 * Effort and rest each get their own voice, so the two are told apart by
 * timbre rather than by counting. A cue is always cut off before the next one
 * opens, so a long gong on a short rest simply stops at the boundary.
 */
export const DEFAULT_GONGS = { work: 'gong-1', rest: 'gong-2' };

export const GONG_ROLES = [
  { role: 'work', label: 'Gong effort', hint: 'Début des 20 s / 30 s' },
  { role: 'rest', label: 'Gong repos', hint: 'Début des 10 s / 20 s' },
];

export function findGong(id) {
  return GONGS.find((g) => g.id === id) || GONGS[0];
}
